name: P1 Hello CI V2

on:
  # push:
  #  branches:
  #    - "**"
  workflow_dispatch:
  
jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print Hello message
        run: |
          echo "Hello Github Actions"

      - name: Print runner info
        run: |
          echo "Runner OS: $RUNNER_OS"
          echo "Branch: $GITHUB_REF"

