name: P1 Hello CI

on:
  push:
    branches:
      -"**"
  workflow_dispatch:
jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print Hello message
        run: |
          echo "Hello Github Actions"
