name: P2 Eventos

on:
  push:
  pull_request:

jobs:
  eventos-test:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar evento que disparo el workflow
        run: |
          echo "Workflow ejecutado por el evento: ${{ github.event_name }}"


