name: P7 Secretos

on:
  push:
    paths:
      - ".github/workflows/P7-Secretos.yml"

jobs:
  demo-secretos:
    runs-on: ubuntu-latest
    
    env:
      JOB_VAR : ${{ secrets.MI_SECRETO }}

    steps:
      - name: Mostrar que el secreto existe
        run: |
          echo "El secreto est√° definido"

      - name: Usar secreto como variable de entorno
        env: 
          MI_SECRETO: ${{ secrets.MI_SECRETO }}
        run: |
          echo "Intentando imprimir el secreto:"
          echo "$MI_SECRETO"

      - name: Verificar comportamiento en logs
        run: |
          echo "Fin del ejercicio"
      
      - name: Extra
        env:
          STEP_VAR : ${{ secrets.MI_SECRETO }}
        run: |
          echo "El secreto a nivel job es $JOB_VAR"
          echo "El secreto a nivel step es $STEP_VAR"
          
