name: P9 Dependencias (Needs)

on:
  push:
    paths:
      - "github/workflows/P9-Dependencias.yml"

jobs:
  job_tests:
    name: Job 1 - Tests

    runs-on: ubuntu-latest

    steps:
      - name: Simular tests
        run: |
          echo "Ejecutando Tests... "
          echo "Tests OK"
  
  job-train:
    name: Job 2 - Train (depende de tests)
    
    runs-on: ubuntu-latest
    
    needs: job_tests

    steps:
      - name: Simular entrenamiento
        run: |
          echo "Entrenando modelo... "
          echo "Modelo entenado"


